sudo: required
services:
  - docker

before_install:

  - docker build -t pi/react -f Dockerfile.dev .

script:
  - docker run -e CI=true pi/react npm run test -- --coverage

deploy:
  provider:elasticbeanstalk
  region:"eu-central-1"
  app:"Docker-react"
  env:"DockerReact-env"
  bucket_path:"Docker-react"
  bucket_name:"elasticbeanstalk-eu-central-1-407283458562"

